# First docker file from bolingcavalry
# VERSION 0.0.1
# Author: bolingcavalry

FROM tomcat:9.0

MAINTAINER "grcheng <grcheung@163.com>"

COPY tomcat-users.xml /usr/local/tomcat/conf/
COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/